### PR TITLE
Update for normalize.css 7.0.0

### PR DESCRIPTION
**Pull request by annaghi**
**elm-package.json**
**examples/elm-package.json**
* version number (Is it a fix?)
* update dependecies

**Normalize.elm**
* update to normalize.css v7.0.0
* qualified names
* elm-format

**examples/Stylesheets.elm**
* update using elm-css 9.0.0
* elm-format

**examples/Main.elm**
* simplify `main` function
* elm-format

### CODE REVIEW

**Comment by scottcorgan** [comment]
This is excellent! I'll review a bit later 👍

**Comment by scottcorgan** [comment]
@bansaghi looks great. Is there anything in particular that I should look at?

If not, I'll go ahead and merge.

**Comment by annaghi** [comment]
Thank you for the quick response! I am happy you like the PR.

Yes, please, check the version number in both elm-package.json files. Everything else is OK.

**Comment by icidasset** [comment]
Any chance this could be merged soon? 🙏  Thanks for the great work both of you!

**Comment by scottcorgan** [comment]
@bansaghi  @icidasset published!

Sorry for the delay 😞

**Comment by icidasset** [comment]
@scottcorgan No problem at all, thanks! 😄

**Comment by annaghi** [comment]
@scottcorgan Thanks for publishing! :dancer:

**Pull request merged**
